wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1665516680.1705
    t:
      1:
      - 2
      - 3
      - 5
      - 16
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 16
      - 53
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 5
      - 9
