---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
        - name: fastapi-server
          image: ghcr.io/ml-in-prod/ml-fast-api:latest
          env:
            - name: WANDB_API_KEY
              value: "wand_api_key"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: fastapi-server
