apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/ml-in-prod/ml-prjctr

---
apiVersion: v1
kind: Service
metadata:
  name: server-node-port
spec:
  type: NodePort
  selector:
    app: server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      protocol: TCP