name: Create K8s Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Apply k8s definitions
        run: kubectl apply -f ./infra/k8s